# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f5f6eabcddaeacf2b6a13bdab98f7e15ba6d18f48a3c1e48a3899c0ad2984cb09d1ffd74ffd44ef3cd35075d0b169f1b441b3abcaf5fedd226e3044dabd5243

test:
  secret_key_base: 42027175dccd12a05b4fe76ab9ba69146a979082573e70a8a294184296d9b158a912b09dc2b39c379efbbe937ddd1dcf81385d7544aa3f56b5f8c2a103b9bf56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
